### ISSUE TITLE
Consider changing from rmm::device_vector to thrust::device_ptr

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/custrings#189]
[https://github.com/rapidsai/custrings/blob/branch-0.4/cpp/src/NVStringsImpl.h](https://github.com/rapidsai/custrings/blob/branch-0.4/cpp/src/NVStringsImpl.h)
 I notice that rmm::device_vector<custring_view*>* pList. I want to be able to generate this from ipc but I can't becuase its using a thrust::device_vector with an RMM allocator. Thrust insists on allocating so I don't have a way of just setting the pointer in question to a ipc memory. 

thrust::device_ptr can be both allocated or created from an ipc'd pointer. The downside would be that we would know have to store the size of our pList since thrust::device_ptr<custring_view*> has no size. We could make alight container that contains all of the methods we are calling in RMM. 

It really shoudl be  possible to ipc things between systems. Right now our solution will be to make a copy and treat strings as "special" assuming they are NEVER ipc'd. When we send them around as ipc payloads we literally allocate a rmm::device_vector and copy from the ipc'd pointer into the newly created allocation that we did not need.

**Comment by davidwendt** [comment]
How about making a copy of the ipc handle data into a pre-allocated device_vector instance.

**Comment by felipeblazing** [comment]
The point of using ipc is not having to make copies and not having to manage the resources there. So we currently have ipc'd tables. So all of the columns that make up our table have arrived and are assumed to have been created using ipc. If I make an allocation and copy the data I have to create special business logic for the fact that these columns CANNOT be ipcd

**Comment by davidwendt** [comment]
There are two parts that need to be copied to the new context. The single memorybuffer holding all the string data (variable length custring_view instances) and the pointer array to each instance (pList). The pList values are pointers for various valid reasons and so they must be fixed up within the new context. The fix up requires this part of the memory (pList) to be copied in order to not mess up the data in the context where the ipc originated. The string/character data (the larger part of this) does not need to be copied. We can contain the ipc handle management, the copy, and the fixup as member data and member functions so the business logic is isolated within the scope of NVStrings.

**Comment by davidwendt** [comment]
Want to use this issue to push PR with code changes to support ipc handles.
