### ISSUE TITLE
[FEA] n-gram function

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#224]
### Description
As a user, I want to create n-grams (most commonly, bigrams) from a corpus in my NLP workflows. Currently, I can do this fairly easily on the CPU with NLTK. It's not straightforward to do the same with custrings. An n-gram function would it nicely in nvtext.

At a high level, I could shift each string forward one (for bigrams) in a new array and concatenate the strings at the same index (old array and new array). Currently, I need to do something like the following:

```
strings = ['this is my favorite', 'book on my bookshelf']
dstrings = nvstrings.to_device(strings)

sentence = dstrings.split_record()
sentence = nvstrings.from_strings(sentence)

pad = nvstrings.to_device([''])
adjusted_sentences = sentence.remove_strings([0])
adjusted_sentences = adjusted_sentences.add_strings(pad)
bigrams_object = sentence.cat(adjusted_sentences, '_')
# need to remove last bigram because its just the last word catted with nothing
bigrams_object = bigrams_object.remove_strings([bigrams_object.size()-1])
print(bigrams_object)
['this_is', 'is_my', 'my_favorite', 'favorite_book', 'book_on', 'on_my', 'my_bookshelf']
```
I need to first split records and then recombine in order to create a single nvstrings instance of all the tokens. Next I create the second array, remove the token at position 0 (to offset by one for bigrams), and pad the end of the array with a blank token (this is due to `cat` requiring arrays of the same length). Then, I can combine the original and offset arrays with `cat`. I then need to remove the last token due to the alignment.

A function like NLTK's `ngrams` would make this process much smoother:

#### CPU NLTK Example
```
from nltk.util import ngrams

strings = ['this is my favorite', 'book on my bookshelf']

def bigramize(line):
    token = line.split()
    return list(ngrams(token, 2))

list(map(bigramize, strings))
[[('this', 'is'), ('is', 'my'), ('my', 'favorite')],
 [('book', 'on'), ('on', 'my'), ('my', 'bookshelf')]]
```
In this example, I don't concatenate. But I could do a `'_'.join()` to actually combine them.

**Comment by randerzander** [comment]
Your implementation of bigrams is clever.

Question: does it generalize to ngrams?

Regardless of the answer, having to write the bigram snippet as you did, while performant and not too hard, is not a friendly user experience. We should provide a simpler API for bigrams.

I envision the nvtext module needing a lot of abstract, non-core string level functionality, like bigrams. That said, I don't feel we're at the right point in the project to spend much time creating CUDA/C++ layer implementations.

But, thanks to the Python bindings, we can still provide nice user-facing APIs in Python, wrapping the types of snippets you wrote above.

For cuDF, we try to keep the Python bindings thin, because the functionality needs to be exposed by C++ to other languages (Java, R, external applications, etc.). I don't think `nvtext` has the same type of external demand, at least presently.

@beckernick I propose you make a PR to nvtext, wrapping bigrams in an end-user friendly method, and simultaneously create a [BACKLOG] labeled issue linked to your PR, noting the need to consider a CUDA/C++ implementation later on.

@davidwendt @kkraus14 thoughts?

**Comment by beckernick** [comment]
I'd be in favor of this as well, but am interested in hearing everyone else's thoughts.

To the specific question of bigrams vs ngrams, the logic above can be generalized to n-grams by wrapping the shifting/padding/concatenation into a loop that is aware of the `N` for N-grams. An example (but likely not optimal) way to do this is:

```
strings = ['this is my favorite', 'book on my bookshelf']
dstrings = nvstrings.to_device(strings)

def ngrams(device_strings, N=2):
    
    tokens = device_strings.split_record()
    tokens_combined = nvstrings.from_strings(tokens)
    ngram_object = tokens_combined
    pad = nvstrings.to_device([''])
    sentence_arrays = []
    
    for i in range(N-1):
        adjusted_sentences = tokens_combined.remove_strings(list(range(0, i+1)))
        adjusted_sentences = adjusted_sentences.add_strings([pad]*(tokens_combined.size()-adjusted_sentences.size()))
        sentence_arrays.append(adjusted_sentences)
        
    for sent in sentence_arrays:
        ngram_object = ngram_object.cat(sent, '_')

    ngram_object = ngram_object.remove_strings(list(range(ngram_object.size()-N+1,ngram_object.size())))
    return ngram_object

print(ngrams(dstrings, 5))
['this_is_my_favorite_book', 'is_my_favorite_book_on', 'my_favorite_book_on_my', 'favorite_book_on_my_bookshelf']

```

**Comment by davidwendt** [comment]
Anything that loops over the number of strings (`dstrings` in the above examples) in CPU code will not perform well for a large number of strings. I will call the number of strings M since you've used N for the number if ngrams. These two lines:
```
tokens = device_strings.split_record()
tokens_combined = nvstrings.from_strings(tokens)
```
will each iterate over M values in CPU code (not parallelized) -- not going to scale well.
These two lines essentially split up the words to just combined them together again into a single _nvstrings_ instance. This is similar to what `unique_tokens()` does except without the unique part, right?
This is probably a common pattern and should become a single `nvtext.tokenize()` method perhaps. Which should be less work than `unique_tokens` since it does not need to sort or unique the tokens.

The rest of it looks good to me since the loops are at most N.

Other than that, I think making the ngram function in python code in `nvtext.py` makes sense. There are other optimizations we could do later in C/C++ code as you mentioned. But I would recommend at least creating the `tokenize()` method (or whatever name makes sense).

**Comment by beckernick** [comment]
Agreed @davidwendt. And yes, this is accomplishing the same tokenizing that exists in `unique_tokens`. To your point, this does not scale well beyond ~20,000 sentences.

I spent some effort trying to figure out how to avoid the CPU iteration, but ultimately still settled on this. I'd be very interested in another approach that avoid this, if one is possible currently. From within Python layer, I couldn't figure out another way to tokenize without using split, which forced me to store the a list of objects on the CPU.

Using `split_record` instead of `split` was necessary because I needed to retain the sentence structure, which columnar `split` followed by `from_strings` does not maintain naturally. I could use `split`, iterate through the CPU list (which to be fair would be much smaller since it's length is determined by the number of tokens in the longest sentence in the corpus, which is usually << the total number of sentences), add each nvstrings as a column in a cudf dataframe, then index select each row of the dataframe and grab the underlying nvstrings object. This seemed much worse, though.

Without avoiding the CPU iteration, we can't scale that well. @randerzander, n-gramizing 20,000 seconds from the public wikipedia data dump take about 5 seconds (there isn't a material difference between the time of bigram, trigram, 5-gram, etc.). Scaling wise, it's roughly 1 additional second per 4000-5000 sentences.
