### ISSUE TITLE
Illegal memory access when using a Alternation in regex

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/custrings#310]
When I use multiple regular expression and check for a match with 25 million records, I get an error : `reduce failed to synchronize: an illegal memory access was encountered`

Exact code:
```
def is_private(df):
    private_REGEX = "(^0\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^10\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^127\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^169\.254\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^172\.(1[6-9]|2[0-9]|3[0-1])\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^192\.0\.0\.([0-7])$)|(^192\.0\.0\.(1(7[0-1]))$)|(^192\.0\.2\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^192\.168\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^198\.(1[8-9])\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^198\.51\.100\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^203\.0\.113\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^(2(4[0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)|(^255\.255\.255\.255$)"
    return df['network'].data.match(private_REGEX)
```

There is no error/stack trace in my notebook but upon checking my console(where juypter notebook is running), this is the Error on console:
```
[I 01:14:26.684 LabApp] Saving file at /IP.ipynb
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  reduce failed to synchronize: an illegal memory access was encountered
[I 01:15:30.512 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 812811ae-d118-4d40-8764-15a357868c46 restarted
[I 01:16:27.813 LabApp] Saving file at /IP.ipynb
```

Here are the unit-tests for the above regex: https://regex101.com/r/oq3PQE/1/tests
In the above link, on the right you can find Explanation of all the alternations I've used.

Note: 
1. This error doesn't come up while I was running against 1000 records. When I bumped up the dataset size to 25million rows, this error occurs. 
2. Also, with 25million rows and single regex, the above code works - there is no error. When more than one regex is used in Alternation, only then I get the above error.

Incase someone needs the data-set please reach out to me on slack(nvidia-internal) as I'm not sure if I'm allowed to publicly share it.

**Comment by davidwendt** [comment]
There is an internal threshold for the number of instructions. Below this threshold, thread stack is used to manage the regex for each string. Above this threshold, global memory is allocated for this. The size of stack is per instruction and the size of the global memory (if needed) is per string per instruction. The limit to the thread stack size is per CUDA capability. The global memory was introduced to accommodate any number of instructions. This is proving impractical since it is based on the number of strings too.

The example regex above actually includes 695 instructions; well beyond the internal threshold of 96. However, 25 million rows for 695 instructions easily exceeds the memory limit on a 16GB GPU card.

My proposal is to increase the threshold for a reasonable stack size and then make it a limit -- return an error when the limit is exceeded. This would also remove the need for the global memory logic. This also means that a long regex with many alternations may need to be split up into multiple calls by the caller. I think supporting many strings is more important than supporting long expressions.

**Comment by davidwendt** [comment]
We've done a little math and found we can increase the threshold from 96 to 1024 instructions since there is plenty of room on the thread stack. After some discussion we will keep the global memory logic but introduce a better error message so the caller has the flexibility to use more instructions over a smaller dataset if needed.
