### ISSUE TITLE
[QST] Why are inplace operations not supported with nvstrings ?

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/custrings#352]
[QST] Why are inplace operations not supported with nvstrings ?

I was wondering because allowing in place operations may help with saving a lot of memory overhead in string heavy workflows. 

Pandas Example:
```python
import pandas as pd
df = pd.DataFrame({'col':['a,b','c,d']})
df['col'].replace(',','-', inplace=True , regex=True)
print(df)
```
Ouput
```
  col
0  a-b
1  c-d
```

**Comment by davidwendt** [comment]
With fixed-width data-types, there is no problem replacing data in-place since the size does not change. In general, in-place operations will not work for variable-length data types (like strings). New memory must be allocated to hold the result. For efficiency, this memory is contiguous with all the other data in the column.

**Comment by VibhuJawa** [comment]
> With fixed-width data-types, there is no problem replacing data in-place since the size does not change. In general, in-place operations will not work for variable-length data types (like strings). New memory must be allocated to hold the result. For efficiency, this memory is contiguous with all the other data in the column.

Yeah. That makes sense. Thanks a lot for answering.
