### ISSUE TITLE
[BUG] Passing out of range index to nvcategory.gather_strings causes a segfault

### ISSUE THREAD

**Issue by beckernick** [rapidsai/custrings#367]
Passing an index to `nvcategory.gather_strings` that is out of bounds for the number of keys causes a segfault. We should protect Python users from this by raising an error.

```python
import nvcategory 
c = nvcategory.to_device(['a','b','c']) 
print(c.gather_strings([0])) 
c.gather_strings([5])                                                                                                             
['a']
Segmentation fault (core dumped)
```

**Comment by jrhemstad** [comment]
I don't think this is really what we should do. 

For example, we don't do anything in libcudf to detect an out of bounds access in a gather.

**Comment by beckernick** [comment]
That's a good point @jrhemstad . Matching libcudf makes sense.

I think we should be careful at the Python level, though. Python users aren't used to segfaults, especially when working in Notebooks. Since a segfault kills the entire kernel, this can be very frustrating in Python land since users will have to run many cells again. If nvcategory is going to be an end-user library at the Python level, I think protecting those users is worthwhile

**Comment by ayushdg** [comment]
Seems like the code actually tries to catch this exception and throw a good error. https://github.com/rapidsai/custrings/blob/branch-0.9/python/cpp/pycategory.cpp#L546

My understanding is that it doesn't get propagated because the `catch` isn't done between the `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS` macros. 

It shouldn't be too tough to modify the behavior in the bindings to properly catch the existing errors and print the intended message.
