### ISSUE TITLE
[BUG] nvstrings.replace `\` doesn't work

### ISSUE THREAD

**Issue by AK-ayush** [rapidsai/custrings#393]
Replacing backslash is not working in nvistrings object.

here is the minimal reproducer...
```python
import nvstrings
s = nvstrings.to_device(["hello\wor-ld","good-bye\\asd"])
print(s.replace('-', ''))
print(s.replace('\\', ''))

out:
['hello\\world', 'goodbye\\asd']
['hello\\wor-ld', 'good-bye\\asd']

```

**Comment by davidwendt** [comment]
So this is actually working correctly. Technically, a single backslash `\` is not allowed and is ignored. There must be a character after it. The `\\` is interpreted by Python as a single `\` and passed into the function and the regex compiler ignores this invalid instruction. Same thing happens with Pandas:
```
import pandas as pd
ps = pd.Series(["hello\\wor-ld","good-bye\\asd"])
print(ps.replace('\\',''))
```
```
0    hello\wor-ld
1    good-bye\asd
```
Also the builtin Python **re** class throws an error:
```
import re
re.sub('hello\\world','\\','')
Traceback (most recent call last):
 ....
re.error: bad escape (end of pattern) at position 0
```
Even passing builtin instructions requires two backslashes as in `s.replace('\\s+','')` this gets passed to the code as `\s+`. If you pass just `\s+` it will not work.

So there are 2 options. 
- Pass 2 backslashes using the form `'\\\\'`  (4 backslashes)
- Use the 'r' prefix to keep Python from interpreting the string: `r'\\'`

```
s = nvstrings.to_device(["hello\\wor-ld","good-bye\\asd"])
print(s.replace('\\\\', ''))
print(s.replace(r'\\', ''))
```
```
['hellowor-ld', 'good-byeasd']
['hellowor-ld', 'good-byeasd']
```

Actually, there is a third option specifically for this case. Do **not use regex** at all here since this is just a single character and regex is overkill and probably slower:
```
s = nvstrings.to_device(["hello\\wor-ld","good-bye\\asd"])
print(s.replace('\\', '', regex=False))
```
```
['hellowor-ld', 'good-byeasd']
```

**Comment by AK-ayush** [comment]
Thanks a lot @davidwendt for such a clear explanation.
